import React from 'react'

const SubHeader = () => {
    return (
        <div className='sub__header__main'>
            <div>
                <div>
                    <div>
                        <div>언어별로 찾아보기</div>
                        <div>
                            <span>선호하는 설정을 선택하세요</span>
                            <div>
                                <div>
                                    <div>
                                        <div>
                                            <div>
                                                <span></span>
                                            </div>
                                            <div>
                                                <ul>
                                                    <li>
                                                        <a></a>
                                                    </li>
                                                    <li>
                                                        <a></a>
                                                    </li>
                                                    <li>
                                                        <a></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <div>
                                        <div>
                                            <span></span>
                                        </div>
                                        <div>
                                            <ul>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                                <li>
                                                    <a></a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <span></span>
                                <div>
                                    <div>
                                        <span></span>
                                    </div>
                                    <div>
                                        <ul>
                                            <li>
                                                <a></a>
                                            </li>
                                            <li>
                                                <a></a>
                                            </li>
                                            <li>
                                                <a></a>
                                            </li>
                                            <li>
                                                <a></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default SubHeader